language: csharp
solution: BulletML.sln
install:
  - nuget restore BulletML.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Tests/Tests.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll